if(EXISTS "C:/software/odevler/ce204-1/ce205-yusufislam-kacar-firat-atalay/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
  include("C:/software/odevler/ce204-1/ce205-yusufislam-kacar-firat-atalay/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
else()
  add_test(utility_tests_NOT_BUILT utility_tests_NOT_BUILT)
endif()
